// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAdR7NVDoolyfkePH0XOEGxV0Ox21ozpSo',
    appId: '1:441503853939:web:43b424f1939653e97c2906',
    messagingSenderId: '441503853939',
    projectId: 'kit305week5tutorial',
    authDomain: 'kit305week5tutorial.firebaseapp.com',
    storageBucket: 'kit305week5tutorial.appspot.com',
    measurementId: 'G-001L4KVY9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1ydb6zSBYXJKrs0Ll-c8ocjFxBwDBBM8',
    appId: '1:441503853939:android:af6925d9091a366a7c2906',
    messagingSenderId: '441503853939',
    projectId: 'kit305week5tutorial',
    storageBucket: 'kit305week5tutorial.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9xEQQr3PfbcIMzVSGRVpfVy3AlUmXKTA',
    appId: '1:441503853939:ios:c320ab268c3b67af7c2906',
    messagingSenderId: '441503853939',
    projectId: 'kit305week5tutorial',
    storageBucket: 'kit305week5tutorial.appspot.com',
    iosBundleId: 'au.utas.edu.nicolynk.cricketappflutter.cricketAppFlutter',
  );
}
